// app/layout.js
import './globals.css'; // <--- Цей рядок обов'язковий!
import Header from '../components/Header'; // Приклад інших імпортів

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body>
        <Header /> {/* Оскільки це Layout, Header буде на всіх сторінках */}
        <main>{children}</main>
      </body>
    </html>
  )
}